### ISSUE TITLE
indexError: list index out of range

### ISSUE THREAD

**Issue by Barlafuss** [sameera-madushan/ISS-Tracker#1]
Traceback (most recent call last):
  File "tracker.py", line 135, in <module>
    main()
  File "tracker.py", line 113, in main
    passes = get_passes()
  File "tracker.py", line 78, in get_passes
    lat = get_coordinates()[1]
IndexError: list index out of range

with debian bullseye/sid x86_64 Kernel: 5.5.0-2-amd64 Python 3.8.3rc1

**Comment by sameera-madushan** [comment]
Which country are you from?

**Comment by Barlafuss** [comment]
Italy (Milan)

**Comment by sameera-madushan** [comment]
Added a fix. Let me know if you still getting the error. Thank you.

**Comment by Barlafuss** [comment]
It works like a charm now, thanks !
